export { default as Navbar } from './Navbar'
export { default as PokemonList } from './PokemonList'
export { default as CardPokemon } from './CardPokemon'
export { default as AvatarPokemon } from './AvatarPokemon'
export { default as BasicInfoPokemon } from './BasicInfoPokemon'
export { default as StatusPokemon } from './StatusPokemon'